concurrent = 1
check_interval = 0

[[runners]]
  name = "runner-ci"
  url = "http://18.222.170.237/"
  token = "60fa3b01c78b3813c3d3a94ac6620c"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "centos"
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
  [runners.cache]
